#' Welch's T-test for identifying isotopic incorporation.
#'
#' @description
#' Compute the full Isotope Matrix, with no natural abundance correction,
#' and no exclusion of isotopic signal using reproducibility thresholds.
#' Then, compare the [M+0] fraction via Welch's t test.
#'
#' Scoring:
#' Anything where the proportion of [M+0] is higher in the labeled samples than unlabeled gets a score of 0.
#' Anything with p > 0.05 gets a score of 0.
#' If a p-value could not be computed, the score is 0.
#' Otherwise, the score is (1 - pvalue) (also called the "confidence level").
#'
#' @param isotope_matrix DataFrame containing a \code{sample} column, and columns
#'   for each isotope, usualy staring with \code{C12 PARENT}. Each row corresponds to a single
#'   isotopic envelope for from a given sample. Usually generated by \code{mzkitcpp::ISO_isotope_matrices()}
#'   followed by \code{to_iso_matrices()}.
#' @param unlabeled_samples sample names corresponding to samples in
#'    representative unlabeled sample set.
#' @param labeled_samples sample names corresponding to samples in
#'    representative labeled sample set.
#'
#' @return score a value from 0 or 1, where values closer to 1 have greater evidence
#' that isotopic incorporation is evident based on the data in the \code{unlabeled_samples}
#' and \code{labeled_samples} in this \code{isotope_matrix}.
#'
#' @export
diff_iso_m_plus_zero_fraction_WelchTTest <- function(isotope_matrix, unlabeled_samples, labeled_samples) {
  unlabeled_envelopes <- isotope_matrix %>% dplyr::filter(sample %in% unlabeled_samples)
  labeled_envelopes <- isotope_matrix %>% dplyr::filter(sample %in% labeled_samples)

  if ("C12 PARENT" %in% colnames(isotope_matrix)) {
    unlabeled_m_plus_zero_fraction <- unlabeled_envelopes$`C12 PARENT`
    labeled_m_plus_zero_fraction <- labeled_envelopes$`C12 PARENT`
  } else if ("[M + 0]" %in% colnames(isotope_matrix)) {
    unlabeled_m_plus_zero_fraction <- unlabeled_envelopes$`[M + 0]`
    labeled_m_plus_zero_fraction <- labeled_envelopes$`[M + 0]`
  } else {
    # If the C12 PARENT isotope / [M+0] isotope is missing from all sample measurements,
    # something pathological has probably happened - but from the point of view of this function,
    # there is no evidence of incorporation
    return(0)
  }

  # explicitly remove any NA values
  unlabeled_m_plus_zero_fraction <- unlabeled_m_plus_zero_fraction[!is.na(unlabeled_m_plus_zero_fraction)]
  labeled_m_plus_zero_fraction <- labeled_m_plus_zero_fraction[!is.na(labeled_m_plus_zero_fraction)]

  # If variability cannot be computed for one set of measurements, t-test cannot be performed.
  # score of 0 indicates no evidence for incorporation.
  if (is.na(var(unlabeled_m_plus_zero_fraction)) || is.na(var(labeled_m_plus_zero_fraction))) {
    return(0)
  }

  # If data has no variability (e.g., data is present by is essentially constant, t-test cannot be performed.)
  # score of "0" indicates no evidence for incorporation.
  if (var(unlabeled_m_plus_zero_fraction) < 1e-10 || var(labeled_m_plus_zero_fraction) < 1e-10) {
    return(0)
  }

  # Welch's t-test
  welch_result <- t.test(unlabeled_m_plus_zero_fraction, labeled_m_plus_zero_fraction)

  # p-value
  welch_p_value <- welch_result$p.value

  # [M+0] should be relatively smaller in the labeled sample set.
  # Otherwise, the signal isn't real / the quant is incorrect.
  is_real_incorporation <- mean(unlabeled_m_plus_zero_fraction) > mean(labeled_m_plus_zero_fraction)

  score <- 0
  if (is_real_incorporation && !is.na(welch_p_value)) {
    score <- -1 * log10(welch_p_value) # Switch from (1-pvalue per #1447)
  }

  return(score)
}

#' Welch's T-test for comparing isotopes in an envelope
#'
#' @description
#' Every isotope in the Isotope Matrix is compared for two conditions
#' Using the Welch T-Test, and a set of p-values are returned.
#'
#' Scoring:
#' A \code{-log10(p-value)} is computed for each kind of isotope.
#' If a p-value cannot be computed, the score is 0 (equivalent to p-value == 1)
#'
#' @param isotope_matrix DataFrame containing a \code{sample} column, and columns
#'   for each isotope, usualy staring with \code{C12 PARENT}. Each row corresponds to a single
#'   isotopic envelope for from a given sample. Usually generated by \code{mzkitcpp::ISO_isotope_matrices()}
#'   followed by \code{to_iso_matrices()}.
#' @param condition_1_samples sample names corresponding to samples in
#'    representative condition 1 sample set (usually control)
#' @param condition_2_samples sample names corresponding to samples in
#'    representative condition 2 sample set (usually non-control)
#'
#' @return tibble of scores (by isotope) as \code{-log10(p_value)}, where higher scores are more significant (lower p-values).
#' that isotopic incorporation is evident based on the data in the \code{condition_1_samples}
#' and \code{condition_1_samples} in this \code{isotope_matrix}.
#'
#' @export
diff_iso_all_isotopes_WelchTTest <- function(isotope_matrix, condition_1_samples, condition_2_samples) {
  condition_1_envelopes <- isotope_matrix %>% dplyr::filter(sample %in% condition_1_samples)
  condition_2_envelopes <- isotope_matrix %>% dplyr::filter(sample %in% condition_2_samples)

  isotope_matrix_cols <- colnames(isotope_matrix)
  isotopes <- isotope_matrix_cols[!grepl("sample", isotope_matrix_cols)]

  t_test_results <- tibble::tibble(
    isotope = isotopes,
    score = rep(0, length(isotopes))
  )

  for (i in 1:length(isotopes)) {
    isotope <- isotopes[i]
    condition_1_measurements <- condition_1_envelopes[, isotope]
    condition_2_measurements <- condition_2_envelopes[, isotope]

    # explicitly remove any NA values
    condition_1_measurements <- condition_1_measurements[!is.na(condition_1_measurements)]
    condition_2_measurements <- condition_2_measurements[!is.na(condition_2_measurements)]

    # If variability cannot be computed for one set of measurements, t-test cannot be performed.
    # score of 0 indicates no evidence for incorporation.
    if (is.na(var(condition_1_measurements)) || is.na(var(condition_2_measurements))) {
      next
    }

    if (var(condition_1_measurements) >= 1e-10 && var(condition_2_measurements) >= 1e-10) {
      welch_result <- t.test(condition_1_measurements, condition_2_measurements)
      welch_p_value <- welch_result$p.value
      if (!is.na(welch_p_value)) {
        t_test_results[i, "score"] <- -1 * log10(welch_p_value)
      }
    }
  }

  return(t_test_results)
}

#' Welch's T-test for comparing isotopes in an envelope
#'
#' @description
#' A subset of samples is first extracted, based on a vector of string regexes.
#' Then, a string regex is used to further organize the remaining sample measurements
#' into either condition_1 or condition_2.
#' The results are passed along into \code{diff_iso_all_isotopes_WelchTTest()}.
#'
#' Scoring:
#' A \code{-log10(p-value)} is computed for each kind of isotope.
#' If a p-value cannot be computed, the score is 0 (equivalent to p-value == 1)
#'
#' @param isotope_matrix DataFrame containing a \code{sample} column, and columns
#'   for each isotope, usualy staring with \code{C12 PARENT}. Each row corresponds to a single
#'   isotopic envelope for from a given sample. Usually generated by \code{mzkitcpp::ISO_isotope_matrices()}
#'   followed by \code{to_iso_matrices()}.
#' @param subset_filters series of regexes that every sample that is to be compared must contain.
#'   This vector input function as an AND filter (all surviving samples match every regex).
#' @param condition_1_regex used to determine sample names corresponding to samples in
#'    representative condition 1 sample set (usually control)
#' @param condition_2_regex used to determine sample names corresponding to samples in
#'    representative condition 2 sample set (usually non-control)
#'
#' @return tibble of scores (by isotope) as \code{-log10(p_value)}, where higher scores are more significant (lower p-values).
#' that isotopic incorporation is evident based on the data in the \code{condition_1_samples}
#' and \code{condition_1_samples} in this \code{isotope_matrix}.
#'
#' @export
diff_iso_all_isotopes_WelchTTest_subset <- function(isotope_matrix, subset_filters, condition_1_regex, condition_2_regex) {
  isotope_matrix_adj <- isotope_matrix
  for (subset_filter in subset_filters) {
    isotope_matrix_adj <- isotope_matrix_adj %>% dplyr::filter(grepl(subset_filter, sample))
  }

  condition_1_samples <- isotope_matrix_adj$sample[grepl(condition_1_regex, isotope_matrix_adj$sample)]
  condition_2_samples <- isotope_matrix_adj$sample[grepl(condition_2_regex, isotope_matrix_adj$sample)]

  return(diff_iso_all_isotopes_WelchTTest(isotope_matrix_adj, condition_1_samples, condition_2_samples))
}


#' Time-Emergent Differential Abundance
#'
#' @description
#' Each sample should contain a covariate 'Time', with implied reference factor level 't_early' and explicit factor level 't_late'.
#' Each sample should contain a covariate 'Treatment', with implied factor level 'control' and explicit factor level 'treatment'.
#'
#' For each isotope, carry out the linear model
#'
#' Measurement ~ Time + Treatment + (Time x Treatment)
#'
#' Assume that the t_early and t_late samples are not from the same subjects - so it would be
#' inappropriate to use a linear mixed effects model.
#
#' Focus on the interaction term (Time x Treatment), looking for a significant p-value.
#'
#' Significance must pass two p-value thresholds, one for the interaction term (must be less than this value),
#' another for the comparison of condition vs treatment for the late time points (must be greater than this value).
#'
#' [2] Follow-up Games-Howell tests focusing on 't_late' vs 't_early' post-hoc comparisons.
#'
#' Ultimately,the difference between treatment and control should
#' (1) SHOULD have a significant \code{p_val_interaction} value,
#' (2) SHOULD NOT have a significant \code{p_val_early_diff} value,
#' (3) SHOULD have a significant \code{p_val_late_diff} value.
#'
#' Significance can be determined downstream by the consideration of these 3 p-values.
#' Scores will often take the form of \code{-log10(p-value)}, where the final score should
#' probably be the \code{p_val_late_diff} value.
#'
#' @param isotope_matrix DataFrame containing isotope measurements.
#' @param is_M0_normalize if \code{TRUE}, every isotope value is divided by the [M+0] value from its respective sample.
#' @param t_early_control_samples sample names corresponding to \code{(Time=t_early, Treatment=control)}
#' @param t_late_control_samples sample names corresponding to \code{(Time=t_late, Treatment=control)}
#' @param t_early_treatment_samples sample names corresponding to \code{(Time=t_early, Treatment=treatment)}
#' @param t_late_treatment_samples sample names corresponding to \code{(Time=t_late, Treatment=treatment)}
#'
#' @returns data frame containing p-value summaries of results.
#' to convert to an overall score, the \code{p_val_interaction} should be BELOW a threshold parameter,
#' (p-value significant)
#' the \code{p_val_early_diff} should be ABOVE a threshold parameter (p-value not significant)
#' the \code{p_val_late_diff} should be BELOW a threshold parameter (p-value significant)
#'
#' For example,
#' let isotope == [M+2], p_val_interaction = 0.0715, p_val_early_diff = 0.693, and p_val_late_diff = 0.0197.
#'
#' let p_val_interaction_thresh = 0.10, p_val_early_thresh = 0.05, p_val_late_thresh = 0.05.
#'
#' This example passes because
#' (1) p_val_interaction = 0.0715 < p_val_interaction_thresh = 0.10 --> PASSES INTERACTION TERM TEST
#' (2) p_val_early_diff = 0.693 > p_val_early_thresh = 0.05 --> PASSES T_EARLY TEST
#' (3) p_val_late_diff = 0.0197 < p_val_late_thresh = 0.05 --> PASSES T_LATE_TEST
#'
#' OVERALL RESULT: this isotope shows time-emergent differential abundance.
#'
#' Intuitively,
#' (1) The delta between treatment and control changes significantly between the early and late time points.
#' (2) There is no significant difference between treatment and control at the early time point.
#' (3) There is a significant difference between treatment and control at the late time point.
#' @export
diff_iso_emergent_significance <- function(
  isotope_matrix,
  is_M0_normalize,
  t_early_control_samples,
  t_late_control_samples,
  t_early_treatment_samples,
  t_late_treatment_samples
) {
  if (is_M0_normalize) {
    isotope_matrix <- to_M0_normalized_isotope_matrix(isotope_matrix)
  }

  isotope_names <- colnames(isotope_matrix)
  isotope_names <- isotope_names[isotope_names != "sample"]
  N <- length(isotope_names)

  results <- tibble::tibble(
    isotope = isotope_names,
    p_val_interaction = rep(NA, N),
    p_val_early_diff = rep(NA, N),
    p_val_late_diff = rep(NA, N)
  )

  for (i in 1:nrow(results)) {
    isotope_name <- isotope_names[i]

    design_matrix <- to_emergent_isotope_design_matrix(
      isotope_matrix,
      isotope_name,
      t_early_control_samples,
      t_late_control_samples,
      t_early_treatment_samples,
      t_late_treatment_samples
    )

    # Step 1: linear model
    model_results <- lm(
      formula = Measurement ~ Treatment * Time,
      data = as.data.frame(design_matrix)
    )
    stats <- summary(model_results)$coefficients

    # initialize output, everything will be passed back and filtering can happen downstream
    p_val_interaction <- NA
    p_val_early_diff <- NA
    p_val_late_diff <- NA

    # Safety check: ensure the interaction wasn't dropped due to singularities (NA)
    if ("Treatment:Time" %in% rownames(stats) && "Treatment" %in% rownames(stats)) {
      p_val_interaction <- stats["Treatment:Time", "Pr(>|t|)"]
      p_val_early_diff <- stats["Treatment", "Pr(>|t|)"]

      # Manual verification: Calculating the 'Late' p-value specifically
      p_val_late_diff <- suppressWarnings(tryCatch(
        {
          late_test <- multcomp::glht(model_results, linfct = c("Treatment + Treatment:Time = 0"))
          as.numeric(summary(late_test)$test$pvalues[1])
        },
        error = function(e) {
          return(NA)
        }
      ))
    }

    results[i, "p_val_interaction"] <- ifelse(is.finite(p_val_interaction), p_val_interaction, NA)
    results[i, "p_val_early_diff"] <- ifelse(is.finite(p_val_early_diff), p_val_early_diff, NA)
    results[i, "p_val_late_diff"] <- ifelse(is.finite(p_val_late_diff), p_val_late_diff, NA)
  }
  return(results)
}
