#' Welch's T-test for identifying isotopic incorporation.
#'
#' @description
#' Compute the full Isotope Matrix, with no natural abundance correction,
#' and no exclusion of isotopic signal using reproducibility thresholds.
#' Then, compare the [M+0] fraction via Welch's t test.
#'
#' Scoring:
#' Anything where the proportion of [M+0] is higher in the labeled samples than unlabeled gets a score of 0.
#' Anything with p > 0.05 gets a score of 0.
#' If a p-value could not be computed, the score is 0.
#' Otherwise, the score is (1 - pvalue) (also called the "confidence level").
#'
#' @param isotope_matrix DataFrame containing a \code{sample} column, and columns
#'   for each isotope, usualy staring with \code{C12 PARENT}. Each row corresponds to a single
#'   isotopic envelope for from a given sample. Usually generated by \code{mzkitcpp::ISO_isotope_matrices()}
#'   followed by \code{to_iso_matrices()}.
#' @param unlabeled_samples sample names corresponding to samples in
#'    representative unlabeled sample set.
#' @param labeled_samples sample names corresponding to samples in
#'    representative labeled sample set.
#'
#' @return score a value from 0 or 1, where values closer to 1 have greater evidence
#' that isotopic incorporation is evident based on the data in the \code{unlabeled_samples}
#' and \code{labeled_samples} in this \code{isotope_matrix}.
#'
#' @export
diff_iso_m_plus_zero_fraction_WelchTTest <- function(isotope_matrix, unlabeled_samples, labeled_samples) {
  unlabeled_envelopes <- isotope_matrix %>% dplyr::filter(sample %in% unlabeled_samples)
  labeled_envelopes <- isotope_matrix %>% dplyr::filter(sample %in% labeled_samples)

  if ("C12 PARENT" %in% colnames(isotope_matrix)) {
    unlabeled_m_plus_zero_fraction <- unlabeled_envelopes$`C12 PARENT`
    labeled_m_plus_zero_fraction <- labeled_envelopes$`C12 PARENT`
  } else if ("[M + 0]" %in% colnames(isotope_matrix)) {
    unlabeled_m_plus_zero_fraction <- unlabeled_envelopes$`[M + 0]`
    labeled_m_plus_zero_fraction <- labeled_envelopes$`[M + 0]`
  } else {
    # If the C12 PARENT isotope / [M+0] isotope is missing from all sample measurements,
    # something pathological has probably happened - but from the point of view of this function,
    # there is no evidence of incorporation
    return(0)
  }

  # explicitly remove any NA values
  unlabeled_m_plus_zero_fraction <- unlabeled_m_plus_zero_fraction[!is.na(unlabeled_m_plus_zero_fraction)]
  labeled_m_plus_zero_fraction <- labeled_m_plus_zero_fraction[!is.na(labeled_m_plus_zero_fraction)]

  # If variability cannot be computed for one set of measurements, t-test cannot be performed.
  # score of 0 indicates no evidence for incorporation.
  if (is.na(var(unlabeled_m_plus_zero_fraction)) || is.na(var(labeled_m_plus_zero_fraction))) {
    return(0)
  }

  # If data has no variability (e.g., data is present by is essentially constant, t-test cannot be performed.)
  # score of "0" indicates no evidence for incorporation.
  if (var(unlabeled_m_plus_zero_fraction) < 1e-10 || var(labeled_m_plus_zero_fraction) < 1e-10) {
    return(0)
  }

  # Welch's t-test
  welch_result <- t.test(unlabeled_m_plus_zero_fraction, labeled_m_plus_zero_fraction)

  # p-value
  welch_p_value <- welch_result$p.value

  # [M+0] should be relatively smaller in the labeled sample set.
  # Otherwise, the signal isn't real / the quant is incorrect.
  is_real_incorporation <- mean(unlabeled_m_plus_zero_fraction) > mean(labeled_m_plus_zero_fraction)

  score <- 0
  if (is_real_incorporation && !is.na(welch_p_value)) {
    score <- -1 * log10(welch_p_value) # Switch from (1-pvalue per #1447)
  }

  return(score)
}

#' Welch's T-test for comparing isotopes in an envelope
#'
#' @description
#' Every isotope in the Isotope Matrix is compared for two conditions
#' Using the Welch T-Test, and a set of p-values are returned.
#'
#' Scoring:
#' A \code{-log10(p-value)} is computed for each kind of isotope.
#' If a p-value cannot be computed, the score is 0 (equivalent to p-value == 1)
#'
#' @param isotope_matrix DataFrame containing a \code{sample} column, and columns
#'   for each isotope, usualy staring with \code{C12 PARENT}. Each row corresponds to a single
#'   isotopic envelope for from a given sample. Usually generated by \code{mzkitcpp::ISO_isotope_matrices()}
#'   followed by \code{to_iso_matrices()}.
#' @param condition_1_samples sample names corresponding to samples in
#'    representative condition 1 sample set (usually control)
#' @param condition_2_samples sample names corresponding to samples in
#'    representative condition 2 sample set (usually non-control)
#'
#' @return tibble of scores (by isotope) as \code{-log10(p_value)}, where higher scores are more significant (lower p-values).
#' that isotopic incorporation is evident based on the data in the \code{condition_1_samples}
#' and \code{condition_1_samples} in this \code{isotope_matrix}.
#'
#' @export
diff_iso_all_isotopes_WelchTTest <- function(isotope_matrix, condition_1_samples, condition_2_samples) {
  condition_1_envelopes <- isotope_matrix %>% dplyr::filter(sample %in% condition_1_samples)
  condition_2_envelopes <- isotope_matrix %>% dplyr::filter(sample %in% condition_2_samples)

  isotope_matrix_cols <- colnames(isotope_matrix)
  isotopes <- isotope_matrix_cols[!grepl("sample", isotope_matrix_cols)]

  t_test_results <- tibble::tibble(
    isotope = isotopes,
    score = rep(0, length(isotopes))
  )

  for (i in 1:length(isotopes)) {
    isotope <- isotopes[i]
    condition_1_measurements <- condition_1_envelopes[, isotope]
    condition_2_measurements <- condition_2_envelopes[, isotope]

    # explicitly remove any NA values
    condition_1_measurements <- condition_1_measurements[!is.na(condition_1_measurements)]
    condition_2_measurements <- condition_2_measurements[!is.na(condition_2_measurements)]

    # If variability cannot be computed for one set of measurements, t-test cannot be performed.
    # score of 0 indicates no evidence for incorporation.
    if (is.na(var(condition_1_measurements)) || is.na(var(condition_2_measurements))) {
      next
    }

    if (var(condition_1_measurements) >= 1e-10 && var(condition_2_measurements) >= 1e-10) {
      welch_result <- t.test(condition_1_measurements, condition_2_measurements)
      welch_p_value <- welch_result$p.value
      if (!is.na(welch_p_value)) {
        t_test_results[i, "score"] <- -1 * log10(welch_p_value)
      }
    }
  }

  return(t_test_results)
}

#' Welch's T-test for comparing isotopes in an envelope
#'
#' @description
#' A subset of samples is first extracted, based on a vector of string regexes.
#' Then, a string regex is used to further organize the remaining sample measurements
#' into either condition_1 or condition_2.
#' The results are passed along into \code{diff_iso_all_isotopes_WelchTTest()}.
#'
#' Scoring:
#' A \code{-log10(p-value)} is computed for each kind of isotope.
#' If a p-value cannot be computed, the score is 0 (equivalent to p-value == 1)
#'
#' @param isotope_matrix DataFrame containing a \code{sample} column, and columns
#'   for each isotope, usualy staring with \code{C12 PARENT}. Each row corresponds to a single
#'   isotopic envelope for from a given sample. Usually generated by \code{mzkitcpp::ISO_isotope_matrices()}
#'   followed by \code{to_iso_matrices()}.
#' @param subset_filters series of regexes that every sample that is to be compared must contain.
#'   This vector input function as an AND filter (all surviving samples match every regex).
#' @param condition_1_regex used to determine sample names corresponding to samples in
#'    representative condition 1 sample set (usually control)
#' @param condition_2_regex used to determine sample names corresponding to samples in
#'    representative condition 2 sample set (usually non-control)
#'
#' @return tibble of scores (by isotope) as \code{-log10(p_value)}, where higher scores are more significant (lower p-values).
#' that isotopic incorporation is evident based on the data in the \code{condition_1_samples}
#' and \code{condition_1_samples} in this \code{isotope_matrix}.
#'
#' @export
diff_iso_all_isotopes_WelchTTest_subset <- function(isotope_matrix, subset_filters, condition_1_regex, condition_2_regex) {
  isotope_matrix_adj <- isotope_matrix
  for (subset_filter in subset_filters) {
    isotope_matrix_adj <- isotope_matrix_adj %>% dplyr::filter(grepl(subset_filter, sample))
  }

  condition_1_samples <- isotope_matrix_adj$sample[grepl(condition_1_regex, isotope_matrix_adj$sample)]
  condition_2_samples <- isotope_matrix_adj$sample[grepl(condition_2_regex, isotope_matrix_adj$sample)]

  return(diff_iso_all_isotopes_WelchTTest(isotope_matrix_adj, condition_1_samples, condition_2_samples))
}


#' Emergent Significance
#'
#' @description
#' Each sample should contain in variable 'Time' factors 't_early' and a 't_late' factor levels.
#' Each sample should contain in 'Treatment' factor 'control' and 'treatment' factor levels.
#'
#' [1] Initial Linear Model
#'
#' For each isotope, carry out the linear model
#'
#' Measurement ~ Time + Treatment + (Time x Treatment)
#'
#' Assume that the t_early and t_late samples are not from the same subjects - so it would be
#' inappropraite to use a linear mixed effects model.
#
#' Focus on the interaction term (Time x Treatment), looking for a significant p-value.
#'
#' [2] Follow-up Games-Howell tests focusing on 't_late' vs 't_early' post-hoc comparisons
#' Demonstrate that t_early is not significant, while t_late is.
#'
#' Scoring:
#' A \code{-log10(p-value)} is computed for each kind of isotope.
#' If a p-value cannot be computed, the score is 0 (equivalent to p-value == 1)
#'
#' @param design_matrix DataFrame consisting of 5 columns, Measurement,
#' Timet_early, Timet_late, Treatmenttreatment, Treatmentcontrol.
#'
#' @export
diff_iso_emergent_significance <- function(
  isotope_matrix,
  is_M0_normalize,
  t_early_control_samples,
  t_late_control_samples,
  t_early_treatment_samples,
  t_late_treatment_samples
) {
  if (is_M0_normalize) {
    isotope_matrix <- to_M0_normalized_isotope_matrix(isotope_matrix)
  }

  isotope_names <- colnames(isotope_matrix)
  isotope_names <- isotope_names[isotope_names != "sample"]

  results <- vector(mode = "list", length = length(isotope_names))
  names(results) <- isotope_names

  for (isotope_name in isotope_names) {
    design_matrix <- to_emergent_isotope_design_matrix(
      isotope_matrix,
      isotope_name,
      t_early_control_samples,
      t_late_control_samples,
      t_early_treatment_samples,
      t_late_treatment_samples
    )

    # Step 1: linear model
    model_results <- lm(
      formula = Measurement ~ Treatmentcontrol * Timelate,
      data = as.data.frame(design_matrix)
    )

    # TODO
  }
}
