#' Get mzrollDB isotopes as long table
#'
#' @description
#' Utility function to pull out pre-computed isotopes (in an mzrollDB) as long table.
#' This works because peakdetector can support isotopic extraction, as part of
#' the mzrollDB generation step. Values are returned exactly as they were computed, though, with no adjustments.
#' Some adjustments are available as options to this function.
#' This function replaces / substitutes in for \code{mzkitcpp::ISO_isotope_matrices()}.
#'
#' Note that this only operates on isotopic peaks - so if an mzrollDB contains a mixture
#' of isotopes and non-isotopes, this will only return back information about the
#' isotopic peaks
#'
#' @param iso_mzrolldb_file full path of mzrollDB file.
#' @param isotope_quant_measurement_type column in \code{peak} table to use for quant.
#' @param is_fractional_abundance [FALSE] if \code{TRUE}, values are returned as fractions of
#'   total isotopic envelope intensity for sample.
#' @param sample_order [NULL] if not \code{NULL}, and a list of sample names, will be used
#' to re-order the table, which may be useful for visualization downstream.
#'
#' @return iso_matrices_df
#'   Long table containing \code{groupId}, \code{groupMz}, \code{sample}, \code{isotope}, \code{measurement}.
#'   Note that \code{groupMz} will be a whole number if \code{is_collapse_nominal} is \code{TRUE}.
#'
#' @export
get_precomputed_iso_df <- function(
  iso_mzrolldb_file,
  isotope_quant_measurement_type = "smoothedPeakArea",
  is_fractional_abundance = FALSE,
  sample_order = NULL
) {
  peaks <- PDB_peaks(iso_mzrolldb_file)
  groups <- PDB_peakgroups(iso_mzrolldb_file)
  samples <- PDB_sample_list(iso_mzrolldb_file)

  peaks_short <- peaks %>%
    dplyr::select(groupId, sampleId, !!rlang::sym(isotope_quant_measurement_type))

  group_parents <- groups %>%
    dplyr::filter(parentGroupId == 0) %>%
    dplyr::select(groupId)

  group_mz_and_rt <- peaks %>%
    dplyr::select(groupId, peakMz, rt) %>%
    dplyr::inner_join(group_parents, by = c("groupId")) %>%
    dplyr::group_by(groupId) %>%
    dplyr::mutate(groupMz = mean(peakMz), groupRt = median(rt)) %>%
    dplyr::ungroup() %>%
    dplyr::select(groupId, groupMz, groupRt) %>%
    dplyr::distinct()

  samples_short <- samples %>%
    dplyr::select(sampleId, name)

  groups_short <- groups %>%
    dplyr::select(groupId, parentGroupId, tagString)

  # groupId, compoundName, adductName, ms2Score, groupMz, groupRt
  groups_header <- groups %>%
    dplyr::select(groupId, compoundName, adductName, ms2Score) %>%
    dplyr::inner_join(group_mz_and_rt, by = c("groupId"))

  precomputed_iso_df <- peaks_short %>%
    dplyr::inner_join(samples_short, by = c("sampleId")) %>%
    dplyr::inner_join(groups_short, by = c("groupId")) %>%
    dplyr::filter(parentGroupId != 0) %>%
    dplyr::select(-groupId, -sampleId) %>%
    dplyr::rename(
      groupId = parentGroupId,
      measurement := !!rlang::sym(isotope_quant_measurement_type),
      sample = name,
      isotope = tagString
    ) %>%
    dplyr::select(groupId, sample, isotope, measurement) %>%
    dplyr::arrange(groupId, sample)

  if (is_fractional_abundance) {
    precomputed_iso_df <- precomputed_iso_df %>%
      dplyr::group_by(groupId, sample) %>%
      dplyr::mutate(envelope_total = sum(measurement)) %>%
      dplyr::ungroup() %>%
      dplyr::mutate(measurement = measurement / envelope_total) %>%
      dplyr::select(-envelope_total)
  }

  if (!is.null(sample_order)) {
    precomputed_iso_df <- precomputed_iso_df %>%
      dplyr::arrange(groupId, sample = forcats::fct_relevel(sample, sample_order)) %>%
      dplyr::mutate(sample = as.character(sample))
  }

  # filter out some strange values which might creep in via weird mzrollDB file
  precomputed_iso_df <- precomputed_iso_df %>%
    dplyr::filter(!is.nan(measurement) & measurement > 0)

  # add header information
  precomputed_iso_df <- precomputed_iso_df %>%
    dplyr::inner_join(groups_header, by = c("groupId"), relationship = "many-to-many") %>%
    dplyr::select(groupId, groupMz, groupRt, compoundName, adductName, ms2Score, sample, isotope, measurement)

  return(precomputed_iso_df)
}

#' Generate quant values as envelope sum
#'
#' @description
#' Using isotopic measurements table as generated by \code{get_precomputed_iso_df},
#' Generate new quantity values for each groupId based on summing across all isotopes.
#'
#' Note that in that table, \code{groupId} actually refers to the parent groupId.
#'
#' For downstream analysis, after using requantified values for \code{groupId},
#' all peak groups with a \code{parentGroupId} mapping to one of these \code{groupIds}
#' should probably be filtered out.
#'
#' @param iso_df: table of isotopic values, computed by \code{get_precomputed_iso_df()}.
#'
#' @returns tibble of \code{envelopeSum} values for each \code{groupId}, e.g.
#' \code{groupId}, \code{sample}, and \code{envelopeSum} columns.
#'
#' @export
requantify_to_envelope_sum <- function(iso_df) {
  iso_df_requantified <- iso_df %>%
    dplyr::select(groupId, sample, isotope, measurement) %>%
    dplyr::group_by(groupId, sample) %>%
    dplyr::mutate(envelopeSum = sum(measurement)) %>%
    dplyr::ungroup() %>%
    dplyr::select(groupId, sample, envelopeSum) %>%
    dplyr::distinct()

  return(iso_df_requantified)
}

#' Utility function to convert long DataFrame into list of IsotopicMatrix tables.
#'
#' @description
#' Designed to convert the output of \code{mzkitcpp::ISO_isotope_matrices()} to
#' a list of tibbles, each of which corresponds to a single isotope matrix.
#' this isotope matrix is an R version of the \code{maven_core IsotopeMatrix} class.
#'
#' @param iso_matrices_df Long dataframe containing columns
#' .  \code{sample}, \code{isotope}, and \code{measurement}, which would typically
#'   be produced by \code{mzkitcpp::ISO_isotope_matrices()}.
#'
#' @return iso_matrices_reshaped: a named list, where entries are isotope matrix
#' data frames (columns: \code{sample}, followed by all individual isotope names;
#' rows: every sample's isotopic envelope).  Entries are named by \code{groupId},
#' and can be accessed, for example, with \code{groupId = 1234} via \code{isotope_matrices_reshaped$`1234`}
#'
#' @export
to_iso_matrices <- function(iso_matrices_df) {
  iso_matrices_nested <- iso_matrices_df %>%
    dplyr::select(groupId, sample, isotope, measurement) %>%
    dplyr::group_by(groupId) %>%
    tidyr::nest()

  iso_matrices_reshaped <- vector(mode = "list", length = length(iso_matrices_nested$groupId))

  for (i in 1:length(iso_matrices_nested$data)) {
    original_tibble <- iso_matrices_nested$data[[i]]

    tibble_reshaped <- original_tibble %>%
      tidyr::pivot_wider(names_from = c("isotope"), values_from = c("measurement"))

    iso_matrices_reshaped[[i]] <- tibble_reshaped
  }
  names(iso_matrices_reshaped) <- as.character(iso_matrices_nested$groupId)

  return(iso_matrices_reshaped)
}

#' Color and re-order samples
#'
#' @description
#' Color samples based on labeled or unlabeled sample group,
#' also try to re-order them based on replicate number.
#'
#' @param samples_tbl mzrollDB samples table, e.g. \code{PDB_sample_list()}.
#' @param unlabeled_samples_pattern string pattern to identify samples in
#'    representative unlabeled sample set.
#' @param labeled_samples_pattern string pattern to identify samples in
#'    representative labeled sample set.
#' @param unlabeled_color color for all unlabeled samples.
#' @param labeled_color color for all labeled samples.
#' @param other_color color to color all samples that match to neither labeled
#' nor unlabeled samples.
#'
#' @return sample table, to be saved to mzrollDB files.
#'
#' @export
diff_iso_color_samples <- function(
  samples_tbl,
  unlabeled_samples_pattern,
  labeled_samples_pattern,
  unlabeled_color = c(0.929334998130799, 0.448004990816116, 0.18019400537014),
  labeled_color = c(0.122087001800537, 0.306293994188309, 0.916074991226196),
  other_color = c(0.5, 0.5, 0.5)
) {
  samples_tbl_recolored <- samples_tbl %>%
    dplyr::mutate(
      color_red = dplyr::case_when(
        grepl(unlabeled_samples_pattern, name) ~ unlabeled_color[1],
        grepl(labeled_samples_pattern, name) ~ labeled_color[1],
        TRUE ~ other_color[1]
      ),
      color_green = dplyr::case_when(
        grepl(unlabeled_samples_pattern, name) ~ unlabeled_color[2],
        grepl(labeled_samples_pattern, name) ~ labeled_color[2],
        TRUE ~ other_color[2]
      ),
      color_blue = dplyr::case_when(
        grepl(unlabeled_samples_pattern, name) ~ unlabeled_color[3],
        grepl(labeled_samples_pattern, name) ~ labeled_color[3],
        TRUE ~ other_color[3]
      ),
      setName = dplyr::case_when(
        grepl(unlabeled_samples_pattern, name) ~ "unlabeled",
        grepl(labeled_samples_pattern, name) ~ "labeled",
        TRUE ~ ""
      ),
    )

  # assume fewer than 100 replicates
  unlabeled_order <- rep(-1, 100)
  labeled_order <- rep(-1, 100)
  other_order <- numeric(0)

  for (i in 1:nrow(samples_tbl_recolored)) {
    sample_id <- samples_tbl_recolored$sampleId[i]
    ith_name <- samples_tbl_recolored$name[i]

    replicate_num <- as.numeric(stringr::str_extract(ith_name, "\\d+(?=\\.mzML$)"))

    # Sample names are not always formatted this way
    if (is.na(replicate_num)) next

    if (grepl(unlabeled_samples_pattern, ith_name)) {
      unlabeled_order[replicate_num] <- sample_id
    } else if (grepl(labeled_samples_pattern, ith_name)) {
      labeled_order[replicate_num] <- sample_id
    } else {
      other_order <- c(other_order, sample_id)
    }
  }

  unlabeled_order <- unlabeled_order[unlabeled_order != -1]
  labeled_order <- labeled_order[labeled_order != -1]

  # elements of order vector are IDs themselves
  updated_order <- c(unlabeled_order, labeled_order, other_order)

  if (length(updated_order) == nrow(samples_tbl_recolored)) {
    samples_tbl_recolored <- samples_tbl_recolored[match(updated_order, samples_tbl_recolored$sampleId), ]
    samples_tbl_recolored <- samples_tbl_recolored %>%
      dplyr::mutate(sampleOrder = dplyr::row_number())
  }

  return(samples_tbl_recolored)
}

#' Generate claman mzroll list from isotopes mzroll db file
#'
#' @description
#' Generate process-ready mzroll from a single mzroll db file, with
#' corresponding method_tag (method name).
#' Note that this function assumes \code{only_identified} is \code{TRUE}.
#' The following rules are applied for peak groups:
#'
#' Peak group filtering step:
#' (1) Remove any unidentified peak groups.
#' (2) Remove peak groups associated with isotopes - they are now accounted for via the envelope summation step.
#' (3) Remove any peak group from a non-Bookmarks search table if a Bookmark with the same name exists.
#' (4) Remove any peak group from a non-Bookmarks search table if multiple copies are found within a non-Bookmarks table.
#' (5) Remove any peak group from the Bookmarks search table if multiple copies are found within the Bookmarks table.
#'
#' Peaks are re-quantified to correspond to the sum of the isotopic envelope, across samples.
#'
#' @param mzroll_db_path path to mzroll DB file,
#'   or a pre-built romic triple_omic object with type tag 'mzroll'.
#'   Callers of this function are responsible for passing in a valid input object
#'   in that use case.  However, the object will still be tested via
#'   \code{test_mzroll_list()}.
#' @param method_tag what method was run (for the purpose of matching
#'   meta-data and aggregating).
#'
#' @return a **triple_omic** from **romic** containing three tibbles:
#' \itemize{
#'   \item{features: one row per unique analyte (defined by a unique
#'     groupId)},
#'   \item{samples: one row per unique sample (defined by a unique sampleId)},
#'   \item{measurements: one row per peak (samples x peakgroups)}
#'   }
#'  And, a design list which tracks the variables in each table.
#'
#' @export
import_isotope_mzroll <- function(mzroll_db_path, method_tag, quant_type = "peakAreaTop") {
  iso_df <- get_precomputed_iso_df(mzroll_db_path, quant_type)
  iso_df_requantified <- requantify_to_envelope_sum(iso_df)

  # import mzrollDB data
  peaks <- PDB_peaks(mzroll_db_path)
  peakgroups <- PDB_peakgroups(mzroll_db_path)
  samples <- PDB_sample_list(mzroll_db_path)

  sample_id_to_name <- samples %>% dplyr::select(sampleId, name)

  # Update peak quantity values from parent peak group to reflect entire isotopic envelope
  updated_quant_vals <- peaks %>%
    dplyr::select(sampleId, peakId, groupId, !!rlang::sym(quant_type)) %>%
    dplyr::inner_join(sample_id_to_name, by = c("sampleId")) %>%
    dplyr::select(-sampleId) %>%
    dplyr::inner_join(iso_df_requantified, by = c("name" = "sample", "groupId")) %>%
    dplyr::select(peakId, envelopeSum) %>%
    dplyr::rename(!!rlang::sym(quant_type) := envelopeSum) %>%
    dplyr::select(peakId, !!rlang::sym(quant_type))

  unmodified_quant_vals <- peaks %>% dplyr::filter(!(peakId %in% updated_quant_vals$peakId))
  modified_quant_vals <- peaks %>%
    dplyr::inner_join(updated_quant_vals, by = c("peakId"), suffix = c(".old", ".new")) %>%
    dplyr::rename(!!rlang::sym(quant_type) := paste0(quant_type, ".new")) %>%
    dplyr::select(dplyr::all_of(colnames(peaks)))

  requantified_peaks <- rbind(unmodified_quant_vals, modified_quant_vals) %>%
    dplyr::arrange(peakId)

  # Peak group filtering step:
  # (1) Remove any unidentified peak groups.
  # (2) Remove peak groups associated with isotopes - they are now accounted for via the envelope summation step.
  # (3) Remove any peak group from a non-Bookmarks search table if a Bookmark with the same name exists.
  # (4) Remove any peak group from a non-Bookmarks search table if multiple copies are found within a non-Bookmarks table.
  # (5) Remove any peak group from the Bookmarks search table if multiple copies are found within the Bookmarks table

  # Remove all bookmarked peak groups if there are multiple entries
  # with the same (compoundName, adductName) name.
  bookmarked_peak_groups <- peakgroups %>%
    dplyr::filter(searchTableName == "Bookmarks" & parentGroupId == 0 & !is.na(compoundName)) %>%
    dplyr::group_by(compoundName, adductName) %>%
    dplyr::mutate(n = dplyr::n()) %>%
    dplyr::ungroup() %>%
    dplyr::filter(n == 1) %>%
    dplyr::select(-n) %>%
    dplyr::mutate(priorityOrder = 1)

  # Remove all non-bookmarked peak groups if there are multiple entries
  # with the same (compoundName, adductName) name.
  identified_peak_groups <- peakgroups %>%
    dplyr::filter(searchTableName != "Bookmarks" & parentGroupId == 0 & !is.na(compoundName)) %>%
    dplyr::group_by(compoundName, adductName) %>%
    dplyr::mutate(n = dplyr::n()) %>%
    dplyr::ungroup() %>%
    dplyr::filter(n == 1) %>%
    dplyr::select(-n) %>%
    dplyr::mutate(priorityOrder = 2)

  # Prefer bookmarked peak groups over non-bookmarked peak groups when determining priority
  final_peak_groups <- rbind(bookmarked_peak_groups, identified_peak_groups) %>%
    dplyr::arrange(compoundName, adductName, priorityOrder) %>%
    dplyr::group_by(compoundName, adductName) %>%
    dplyr::slice(1) %>%
    dplyr::ungroup()

  updated_peakgroups <- final_peak_groups %>%
    dplyr::select(dplyr::all_of(colnames(peakgroups)))

  updated_peaks <- requantified_peaks %>%
    dplyr::filter(groupId %in% updated_peakgroups$groupId)

  # Begin claman transformation functions

  mz_rt_coords <- updated_peaks %>%
    dplyr::mutate(quant_value := !!rlang::sym(quant_type)) %>%
    dplyr::group_by(groupId) %>%
    dplyr::summarize(
      mz = sum(peakMz * quant_value) / sum(quant_value),
      rt = sum(rt * quant_value) / sum(quant_value)
    )

  clamanized_peakgroups <- updated_peakgroups %>%
    dplyr::inner_join(mz_rt_coords, by = c("groupId")) %>%
    dplyr::select(-compoundId) %>%
    dplyr::mutate(compoundName = ifelse(
      is.na(displayName),
      compoundName,
      displayName
    ))

  # validation test
  clamanized_counts <- clamanized_peakgroups %>%
    dplyr::inner_join(updated_peaks, by = c("groupId")) %>%
    dplyr::group_by(compoundName) %>%
    dplyr::mutate(num_samples = dplyr::n()) %>%
    dplyr::ungroup() %>%
    dplyr::select(groupId, compoundName, num_samples) %>%
    dplyr::distinct() %>%
    dplyr::arrange(desc(num_samples), groupId)

  clamanized_peakgroups <- claman:::process_mzroll_identify_peakgroups(
    clamanized_peakgroups,
    only_identified = TRUE
  )

  possible_peakgroup_reduced_vars <- c(
    "groupId",
    "compoundName",
    "smiles",
    "adductName",
    "tagString",
    "is_unknown",
    "mz",
    "rt",
    "systematicCompoundId",
    "compoundDB",
    "searchTableName",
    "label"
  )

  detected_peakgroup_reduced_vars <- intersect(
    possible_peakgroup_reduced_vars,
    colnames(clamanized_peakgroups)
  )

  clamanized_peakgroups <- clamanized_peakgroups %>%
    dplyr::select(!!!rlang::syms(detected_peakgroup_reduced_vars)) %>%
    dplyr::group_by(compoundName) %>%
    dplyr::mutate(peak_label = dplyr::case_when(
      dplyr::n() == 1 ~ compoundName,
      TRUE ~ paste0(compoundName, " (", 1:dplyr::n(), ")")
    )) %>%
    dplyr::ungroup() %>%
    dplyr::mutate(method_tag = method_tag) %>%
    dplyr::arrange(groupId)

  # clamanize samples
  clamanized_samples <- samples %>%
    dplyr::arrange(sampleId) %>%
    dplyr::mutate(
      sampleId = factor(sampleId, levels = sampleId)
    )

  # Need to create a version where groupId is not a factor (for joining)
  # as well as on where groupId is a factor (for validation)
  clamanized_peakgroups_final <- clamanized_peakgroups %>%
    dplyr::mutate(groupId = factor(groupId, levels = groupId)) %>%
    dplyr::mutate(smiles = "")

  # clamanize peaks
  clamanized_peaks <- updated_peaks %>%
    dplyr::mutate(groupId = as.integer(groupId)) %>%
    dplyr::arrange(groupId, sampleId) %>%
    dplyr::mutate(quant_value = !!sym(quant_type)) %>%
    dplyr::mutate(quant_value = as.numeric(quant_value)) %>%
    dplyr::group_by(groupId) %>%
    dplyr::mutate(
      log2_abundance = log2(quant_value),
      centered_log2_abundance = log2_abundance - mean(log2_abundance)
    ) %>%
    dplyr::select(
      groupId,
      sampleId,
      log2_abundance,
      centered_log2_abundance
    ) %>%
    dplyr::ungroup() %>%
    dplyr::mutate(
      groupId = factor(
        groupId,
        levels = levels(clamanized_peakgroups_final$groupId)
      ),
      sampleId = factor(
        sampleId,
        levels = levels(clamanized_samples$sampleId)
      )
    )

  # validation test
  clamanized_peaks_check <- clamanized_peaks %>%
    dplyr::mutate(groupId = as.integer(groupId)) %>%
    dplyr::group_by(groupId, sampleId) %>%
    dplyr::mutate(n = dplyr::n()) %>%
    dplyr::ungroup() %>%
    dplyr::filter(n > 1)

  mzroll_list <- romic::create_triple_omic(
    measurement_df = clamanized_peaks,
    feature_df = clamanized_peakgroups_final,
    sample_df = clamanized_samples,
    feature_pk = "groupId",
    sample_pk = "sampleId",
    omic_type_tag = "mzroll"
  )

  return(mzroll_list)
}

#' Normalize isotope matrix to sample \code{[M+0]}
#'
#' @description
#' Divide all non-M0 isotopes by M0 isotope abundance.
#' \code{NA} values are retained as \code{NA}.
#' Peaks are re-quantified to correspond to the sum of the isotopic envelope, across samples.
#'
#' @return norm_isotope_matrix normalized isotope matrix
#' @export
to_M0_normalized_isotope_matrix <- function(
  isotope_matrix
) {
  isotope_matrix_norm <- isotope_matrix

  norm_col <- isotope_matrix[, "C12 PARENT"]
  cols_to_norm <- colnames(isotope_matrix)
  cols_to_norm <- cols_to_norm[cols_to_norm != "sample"]

  for (col_to_norm in cols_to_norm) {
    isotope_matrix_norm[, col_to_norm] <- isotope_matrix[, col_to_norm] / norm_col
  }

  return(isotope_matrix_norm)
}

#' Isotope-specific design matrix
#'
#' @description
#' Generate a linear-model ready design matrix from a peak group isotope_matrix,
#' specific isotope, and categorizations related to samples data.
#'
#' The specific quantified isotope is renamed to 'Measurement'.
#'
#' The quant values are also \code{log2}-transformed.
#' Any \code{NA}-values are filtered out.
#'
#' @returns design_matrix DataFrame consisting of 3 columns: \code{Measurement},
#' \code{Treatment}, and \code{Time}. The implied reference conditions are
#' understood to be \code{treatment} and \code{t_early}.
#' The provided columns are non-reference factor levels.
#'
#' @export
to_emergent_isotope_design_matrix <- function(
  isotope_matrix,
  isotope_name,
  t_early_control_samples,
  t_early_treatment_samples,
  t_late_control_samples,
  t_late_treatment_samples
) {
  # adjust data frame appropriately
  design_matrix <- isotope_matrix %>%
    # remove any samples that are not covered by the quant matrix
    dplyr::filter(sample %in% t_early_control_samples | sample %in% t_late_control_samples | sample %in% t_early_treatment_samples | sample %in% t_late_treatment_samples) %>%
    # add logic colums
    dplyr::mutate(Treatment = as.integer(sample %in% t_early_treatment_samples | sample %in% t_late_treatment_samples)) %>%
    dplyr::mutate(Time = as.integer(sample %in% t_late_control_samples | sample %in% t_late_treatment_samples)) %>%
    # rename and transform quant data
    dplyr::rename(Measurement := !!rlang::sym(isotope_name)) %>%
    dplyr::mutate(Measurement = log2(Measurement)) %>%
    # remove quantities that are not evaluatable
    dplyr::filter(!is.na(Measurement)) %>%
    dplyr::select(Measurement, Treatment, Time)

  return(design_matrix)
}

#' Determine Isotopic Incorporation
#'
#' @description
#' Generate a linear-model ready design matrix from a peak group isotope_matrix,
#' specific isotope, and categorizations related to samples data.
#'
#' The specific quantified isotope is renamed to 'Measurement'.
#'
#' The quant values are also \code{log2}-transformed.
#' Any \code{NA}-values are filtered out.
#'
#' @returns design_matrix DataFrame consisting of 3 columns: \code{Measurement},
#' \code{Treatment}, and \code{Time}. The implied reference conditions are
#' understood to be \code{treatment} and \code{t_early}.
#' The provided columns are non-reference factor levels.
#'
#' @export
compute_isotopic_incorporation <- function(
  mzrolldb_file_path,
  isotope_quant_measurement_type,
  t_early_control_samples,
  t_early_treatment_samples,
  t_late_control_samples,
  t_late_treatment_samples,
  sample_order
) {
  iso_matrices_df <- get_precomputed_iso_df(
    iso_mzrolldb_file = mzrolldb_file_path,
    isotope_quant_measurement_type = isotope_quant_measurement_type,
    is_fractional_abundance = TRUE,
    sample_order = sample_order
  )

  iso_matrices_df_header <- iso_matrices_df %>%
    dplyr::select(groupId, groupMz, groupRt, compoundName, adductName, ms2Score) %>%
    dplyr::distinct()

  iso_matrices_list <- to_iso_matrices(iso_matrices_df)

  # Control t_early vs Control t_late
  incorporation_scores_control <- purrr::map(
    iso_matrices_list,
    metisotopes::diff_iso_m_plus_zero_fraction_WelchTTest,
    t_early_control_samples,
    t_late_control_samples
  )

  control_scores_tibble <- tibble::tibble(
    groupId = as.integer(names(incorporation_scores_control)),
    groupRank = unlist(incorporation_scores_control),
    subset = "Control"
  ) %>%
    dplyr::inner_join(iso_matrices_df_header, by = c("groupId"))

  # Treatment t_early vs Treatment t_late
  incorporation_scores_treatment <- purrr::map(
    iso_matrices_list,
    metisotopes::diff_iso_m_plus_zero_fraction_WelchTTest,
    t_early_treatment_samples,
    t_late_treatment_samples
  )

  treatment_scores_tibble <- tibble::tibble(
    groupId = as.integer(names(incorporation_scores_treatment)),
    groupRank = unlist(incorporation_scores_treatment),
    subset = "Treatment"
  ) %>%
    dplyr::inner_join(iso_matrices_df_header, by = c("groupId"))

  # Agglomerated incorporation score list - significant in either case
  isotopic_incorporation_scores <- rbind(control_scores_tibble, treatment_scores_tibble) %>%
    dplyr::arrange(desc(groupRank)) %>%
    dplyr::select(groupId, groupMz, groupRt, compoundName, adductName, ms2Score, groupRank, subset)

  return(isotopic_incorporation_scores)

  # sig_scores <- isotopic_incorporation_scores %>%
  #    dplyr::filter(groupRank >= incorporation_score_threshold)

  # incorporation_group_ids <- as.character(unique(sig_scores$groupId))
}
