#' Get mzrollDB isotopes as long table
#'
#' @description
#' Utility function to pull out pre-computed isotopes (in an mzrollDB) as long table.
#' This works because peakdetector can support isotopic extraction, as part of
#' the mzrollDB generation step. Values are returned exactly as they were computed, though, with no adjustments.
#' Some adjustments are available as options to this function.
#' This function replaces / substitutes in for \code{mzkitcpp::ISO_isotope_matrices()}.
#'
#' Note that this only operates on isotopic peaks - so if an mzrollDB contains a mixture
#' of isotopes and non-isotopes, this will only return back information about the
#' isotopic peaks
#'
#' @param iso_mzrolldb_file full path of mzrollDB file.
#' @param isotope_quant_measurement_type column in \code{peak} table to use for quant.
#' @param is_fractional_abundance [FALSE] if \code{TRUE}, values are returned as fractions of
#'   total isotopic envelope intensity for sample.
#' @param sample_order [NULL] if not \code{NULL}, and a list of sample names, will be used
#' to re-order the table, which may be useful for visualization downstream.
#'
#' @return iso_matrices_df
#'   Long table containing \code{groupId}, \code{groupMz}, \code{sample}, \code{isotope}, \code{measurement}.
#'   Note that \code{groupMz} will be a whole number if \code{is_collapse_nominal} is \code{TRUE}.
#'
#' @export
get_precomputed_iso_df <- function(
  iso_mzrolldb_file,
  isotope_quant_measurement_type = "smoothedPeakArea",
  is_fractional_abundance = FALSE,
  sample_order = NULL
) {
  peaks<-PDB_peaks(iso_mzrolldb_file)
  groups<-PDB_peakgroups(iso_mzrolldb_file)
  samples <- PDB_sample_list(iso_mzrolldb_file)

  peaks_short <- peaks %>%
    dplyr::select(groupId, sampleId, !!rlang::sym(isotope_quant_measurement_type))

  group_parents <- groups %>%
    dplyr::filter(parentGroupId == 0) %>%
    dplyr::select(groupId)

  group_mz_and_rt <- peaks %>%
    dplyr::select(groupId, peakMz, rt) %>%
    dplyr::inner_join(group_parents, by = c("groupId")) %>%
    dplyr::group_by(groupId) %>%
    dplyr::mutate(groupMz = mean(peakMz), groupRt = median(rt)) %>%
    dplyr::ungroup() %>%
    dplyr::select(groupId, groupMz, groupRt) %>%
    dplyr::distinct()

  samples_short <- samples %>%
    dplyr::select(sampleId, name)

  groups_short <- groups %>%
    dplyr::select(groupId, parentGroupId, tagString)

  # groupId, compoundName, adductName, ms2Score, groupMz, groupRt
  groups_header <- groups %>%
    dplyr::select(groupId, compoundName, adductName, ms2Score) %>%
    dplyr::inner_join(group_mz_and_rt, by = c("groupId"))

  precomputed_iso_df <- peaks_short %>%
    dplyr::inner_join(samples_short, by = c("sampleId")) %>%
    dplyr::inner_join(groups_short, by = c("groupId")) %>%
    dplyr::filter(parentGroupId != 0) %>%
    dplyr::select(-groupId, -sampleId) %>%
    dplyr::rename(
      groupId = parentGroupId,
      measurement := !!rlang::sym(isotope_quant_measurement_type),
      sample = name,
      isotope = tagString
    ) %>%
    dplyr::select(groupId, sample, isotope, measurement) %>%
    dplyr::arrange(groupId, sample)

  if (is_fractional_abundance) {
    precomputed_iso_df <- precomputed_iso_df %>%
      dplyr::group_by(groupId, sample) %>%
      dplyr::mutate(envelope_total = sum(measurement)) %>%
      dplyr::ungroup() %>%
      dplyr::mutate(measurement = measurement / envelope_total) %>%
      dplyr::select(-envelope_total)
  }

  if (!is.null(sample_order)) {
    precomputed_iso_df <- precomputed_iso_df %>%
      dplyr::arrange(
        groupId,
        sample = forcats::fct_relevel(sample, sample_order)
      ) %>%
      dplyr::mutate(sample = as.character(sample))
  }

  # filter out some strange values which might creep in via weird mzrollDB file
  precomputed_iso_df <- precomputed_iso_df %>%
    dplyr::filter(!is.nan(measurement) & measurement > 0)

  # add header information
  precomputed_iso_df <- precomputed_iso_df %>%
    dplyr::inner_join(
      groups_header,
      by = c("groupId"),
      relationship = "many-to-many"
    ) %>%
    dplyr::select(
      groupId,
      groupMz,
      groupRt,
      compoundName,
      adductName,
      ms2Score,
      sample,
      isotope,
      measurement
    )

  return(precomputed_iso_df)
}

#' Generate quant values as envelope sum
#'
#' @description
#' Using isotopic measurements table as generated by \code{get_precomputed_iso_df},
#' Generate new quantity values for each groupId based on summing across all isotopes.
#'
#' Note that in that table, \code{groupId} actually refers to the parent groupId.
#'
#' For downstream analysis, after using requantified values for \code{groupId},
#' all peak groups with a \code{parentGroupId} mapping to one of these \code{groupIds}
#' should probably be filtered out.
#'
#' @param iso_df: table of isotopic values, computed by \code{get_precomputed_iso_df()}.
#'
#' @returns tibble of \code{envelopeSum} values for each \code{groupId}, e.g.
#' \code{groupId}, \code{sample}, and \code{envelopeSum} columns.
#'
#' @export
requantify_to_envelope_sum <- function(iso_df) {
  iso_df_requantified <- iso_df %>%
    dplyr::select(groupId, sample, isotope, measurement) %>%
    dplyr::group_by(groupId, sample) %>%
    dplyr::mutate(envelopeSum = sum(measurement)) %>%
    dplyr::ungroup() %>%
    dplyr::select(groupId, sample, envelopeSum) %>%
    dplyr::distinct()

  return(iso_df_requantified)
}

#' Utility function to convert long DataFrame into list of IsotopicMatrix tables.
#'
#' @description
#' Designed to convert the output of \code{mzkitcpp::ISO_isotope_matrices()} to
#' a list of tibbles, each of which corresponds to a single isotope matrix.
#' this isotope matrix is an R version of the \code{maven_core IsotopeMatrix} class.
#'
#' @param iso_matrices_df Long dataframe containing columns
#' .  \code{sample}, \code{isotope}, and \code{measurement}, which would typically
#'   be produced by \code{mzkitcpp::ISO_isotope_matrices()}.
#'
#' @return iso_matrices_reshaped: a named list, where entries are isotope matrix
#' data frames (columns: \code{sample}, followed by all individual isotope names;
#' rows: every sample's isotopic envelope).  Entries are named by \code{groupId},
#' and can be accessed, for example, with \code{groupId = 1234} via \code{isotope_matrices_reshaped$`1234`}
#'
#' @export
to_iso_matrices <- function(iso_matrices_df) {
  iso_matrices_nested <- iso_matrices_df %>%
    dplyr::select(groupId, sample, isotope, measurement) %>%
    dplyr::group_by(groupId) %>%
    tidyr::nest()

  iso_matrices_reshaped <- vector(
    mode = "list",
    length = length(iso_matrices_nested$groupId)
  )

  for (i in seq_along(iso_matrices_nested$data)) {
    original_tibble <- iso_matrices_nested$data[[i]]

    tibble_reshaped <- original_tibble %>%
      tidyr::pivot_wider(
        names_from = c("isotope"),
        values_from = c("measurement")
      )

    iso_matrices_reshaped[[i]] <- tibble_reshaped
  }
  names(iso_matrices_reshaped) <- as.character(iso_matrices_nested$groupId)

  return(iso_matrices_reshaped)
}

#' Color and re-order samples
#'
#' @description
#' Color samples based on labeled or unlabeled sample group,
#' also try to re-order them based on replicate number.
#'
#' @param samples_tbl mzrollDB samples table, e.g. \code{PDB_sample_list()}.
#' @param unlabeled_samples_pattern string pattern to identify samples in
#'    representative unlabeled sample set.
#' @param labeled_samples_pattern string pattern to identify samples in
#'    representative labeled sample set.
#' @param unlabeled_color color for all unlabeled samples.
#' @param labeled_color color for all labeled samples.
#' @param other_color color to color all samples that match to neither labeled
#' nor unlabeled samples.
#'
#' @return sample table, to be saved to mzrollDB files.
#'
#' @export
diff_iso_color_samples <- function(
  samples_tbl,
  unlabeled_samples_pattern,
  labeled_samples_pattern,
  unlabeled_color = c(0.929334998130799, 0.448004990816116, 0.18019400537014),
  labeled_color = c(0.122087001800537, 0.306293994188309, 0.916074991226196),
  other_color = c(0.5, 0.5, 0.5)
) {
  samples_tbl_recolored <- samples_tbl %>%
    dplyr::mutate(
      color_red = dplyr::case_when(
        grepl(unlabeled_samples_pattern, name) ~ unlabeled_color[1],
        grepl(labeled_samples_pattern, name) ~ labeled_color[1],
        TRUE ~ other_color[1]
      ),
      color_green = dplyr::case_when(
        grepl(unlabeled_samples_pattern, name) ~ unlabeled_color[2],
        grepl(labeled_samples_pattern, name) ~ labeled_color[2],
        TRUE ~ other_color[2]
      ),
      color_blue = dplyr::case_when(
        grepl(unlabeled_samples_pattern, name) ~ unlabeled_color[3],
        grepl(labeled_samples_pattern, name) ~ labeled_color[3],
        TRUE ~ other_color[3]
      ),
      setName = dplyr::case_when(
        grepl(unlabeled_samples_pattern, name) ~ "unlabeled",
        grepl(labeled_samples_pattern, name) ~ "labeled",
        TRUE ~ ""
      ),
    )

  # assume fewer than 100 replicates
  unlabeled_order <- rep(-1, 100)
  labeled_order <- rep(-1, 100)
  other_order <- numeric(0)

  for (i in seq_len(nrow(samples_tbl_recolored))) {
    sample_id <- samples_tbl_recolored$sampleId[i]
    ith_name <- samples_tbl_recolored$name[i]

    replicate_num <- as.numeric(stringr::str_extract(
      ith_name,
      "\\d+(?=\\.mzML$)"
    ))

    # Sample names are not always formatted this way
    if (is.na(replicate_num)) {
      next
    }

    if (grepl(unlabeled_samples_pattern, ith_name)) {
      unlabeled_order[replicate_num] <- sample_id
    } else if (grepl(labeled_samples_pattern, ith_name)) {
      labeled_order[replicate_num] <- sample_id
    } else {
      other_order <- c(other_order, sample_id)
    }
  }

  unlabeled_order <- unlabeled_order[unlabeled_order != -1]
  labeled_order <- labeled_order[labeled_order != -1]

  # elements of order vector are IDs themselves
  updated_order <- c(unlabeled_order, labeled_order, other_order)

  if (length(updated_order) == nrow(samples_tbl_recolored)) {
    samples_tbl_recolored <- samples_tbl_recolored[
      match(updated_order, samples_tbl_recolored$sampleId),
    ]
    samples_tbl_recolored <- samples_tbl_recolored %>%
      dplyr::mutate(sampleOrder = dplyr::row_number())
  }

  return(samples_tbl_recolored)
}

#' Generate claman mzroll list from isotopes mzroll db file
#'
#' @description
#' Generate process-ready mzroll from a single mzroll db file, with
#' corresponding method_tag (method name).
#' Note that this function assumes \code{only_identified} is \code{TRUE}.
#' The following rules are applied for peak groups:
#'
#' Peak group filtering step:
#' (1) Remove any unidentified peak groups.
#' (2) Remove peak groups associated with isotopes - they are now accounted for via the envelope summation step.
#' (3) Remove any peak group from a non-Bookmarks search table if a Bookmark with the same name exists.
#' (4) Remove any peak group from a non-Bookmarks search table if multiple copies are found within a non-Bookmarks table.
#' (5) Remove any peak group from the Bookmarks search table if multiple copies are found within the Bookmarks table.
#'
#' Peaks are re-quantified to correspond to the sum of the isotopic envelope, across samples.
#'
#' @param mzroll_db_path path to mzroll DB file,
#'   or a pre-built romic triple_omic object with type tag 'mzroll'.
#'   Callers of this function are responsible for passing in a valid input object
#'   in that use case.  However, the object will still be tested via
#'   \code{test_mzroll_list()}.
#' @param method_tag what method was run (for the purpose of matching
#'   meta-data and aggregating).
#'
#' @return a **triple_omic** from **romic** containing three tibbles:
#' \itemize{
#'   \item{features: one row per unique analyte (defined by a unique
#'     groupId)},
#'   \item{samples: one row per unique sample (defined by a unique sampleId)},
#'   \item{measurements: one row per peak (samples x peakgroups)}
#'   }
#'  And, a design list which tracks the variables in each table.
#'
#' @export
import_isotope_mzroll <- function(
  mzroll_db_path,
  method_tag,
  quant_type = "peakAreaTop"
) {
  iso_df <- get_precomputed_iso_df(mzroll_db_path, quant_type)
  iso_df_requantified <- requantify_to_envelope_sum(iso_df)

  # import mzrollDB data
  peaks <- PDB_peaks(mzroll_db_path)
  peakgroups <- PDB_peakgroups(mzroll_db_path)
  samples <- PDB_sample_list(mzroll_db_path)

  sample_id_to_name <- samples %>% dplyr::select(sampleId, name)

  # Update peak quantity values from parent peak group to reflect entire isotopic envelope
  updated_quant_vals <- peaks %>%
    dplyr::select(sampleId, peakId, groupId, !!rlang::sym(quant_type)) %>%
    dplyr::inner_join(sample_id_to_name, by = c("sampleId")) %>%
    dplyr::select(-sampleId) %>%
    dplyr::inner_join(
      iso_df_requantified,
      by = c("name" = "sample", "groupId")
    ) %>%
    dplyr::select(peakId, envelopeSum) %>%
    dplyr::rename(!!rlang::sym(quant_type) := envelopeSum) %>%
    dplyr::select(peakId, !!rlang::sym(quant_type))

  unmodified_quant_vals <- peaks %>%
    dplyr::filter(!(peakId %in% updated_quant_vals$peakId))
  modified_quant_vals <- peaks %>%
    dplyr::inner_join(
      updated_quant_vals,
      by = c("peakId"),
      suffix = c(".old", ".new")
    ) %>%
    dplyr::rename(!!rlang::sym(quant_type) := paste0(quant_type, ".new")) %>%
    dplyr::select(dplyr::all_of(colnames(peaks)))

  requantified_peaks <- rbind(unmodified_quant_vals, modified_quant_vals) %>%
    dplyr::arrange(peakId)

  # Peak group filtering step:
  # (1) Remove any unidentified peak groups.
  # (2) Remove peak groups associated with isotopes - they are now accounted for via the envelope summation step.
  # (3) Remove any peak group from a non-Bookmarks search table if a Bookmark with the same name exists.
  # (4) Remove any peak group from a non-Bookmarks search table if multiple copies are found within a non-Bookmarks table.
  # (5) Remove any peak group from the Bookmarks search table if multiple copies are found within the Bookmarks table

  # Remove all bookmarked peak groups if there are multiple entries
  # with the same (compoundName, adductName) name.
  bookmarked_peak_groups <- peakgroups %>%
    dplyr::filter(
      searchTableName == "Bookmarks" & parentGroupId == 0 & !is.na(compoundName)
    ) %>%
    dplyr::group_by(compoundName, adductName) %>%
    dplyr::mutate(n = dplyr::n()) %>%
    dplyr::ungroup() %>%
    dplyr::filter(n == 1) %>%
    dplyr::select(-n) %>%
    dplyr::mutate(priorityOrder = 1)

  # Remove all non-bookmarked peak groups if there are multiple entries
  # with the same (compoundName, adductName) name.
  identified_peak_groups <- peakgroups %>%
    dplyr::filter(
      searchTableName != "Bookmarks" & parentGroupId == 0 & !is.na(compoundName)
    ) %>%
    dplyr::group_by(compoundName, adductName) %>%
    dplyr::mutate(n = dplyr::n()) %>%
    dplyr::ungroup() %>%
    dplyr::filter(n == 1) %>%
    dplyr::select(-n) %>%
    dplyr::mutate(priorityOrder = 2)

  # Prefer bookmarked peak groups over non-bookmarked peak groups when determining priority
  final_peak_groups <- rbind(bookmarked_peak_groups, identified_peak_groups) %>%
    dplyr::arrange(compoundName, adductName, priorityOrder) %>%
    dplyr::group_by(compoundName, adductName) %>%
    dplyr::slice(1) %>%
    dplyr::ungroup()

  updated_peakgroups <- final_peak_groups %>%
    dplyr::select(dplyr::all_of(colnames(peakgroups)))

  updated_peaks <- requantified_peaks %>%
    dplyr::filter(groupId %in% updated_peakgroups$groupId)

  # Begin claman transformation functions

  mz_rt_coords <- updated_peaks %>%
    dplyr::mutate(quant_value := !!rlang::sym(quant_type)) %>%
    dplyr::group_by(groupId) %>%
    dplyr::summarize(
      mz = sum(peakMz * quant_value) / sum(quant_value),
      rt = sum(rt * quant_value) / sum(quant_value)
    )

  clamanized_peakgroups <- updated_peakgroups %>%
    dplyr::inner_join(mz_rt_coords, by = c("groupId")) %>%
    dplyr::select(-compoundId) %>%
    dplyr::mutate(
      compoundName = ifelse(
        is.na(displayName),
        compoundName,
        displayName
      )
    )

  # validation test
  clamanized_counts <- clamanized_peakgroups %>%
    dplyr::inner_join(updated_peaks, by = c("groupId")) %>%
    dplyr::group_by(compoundName) %>%
    dplyr::mutate(num_samples = dplyr::n()) %>%
    dplyr::ungroup() %>%
    dplyr::select(groupId, compoundName, num_samples) %>%
    dplyr::distinct() %>%
    dplyr::arrange(desc(num_samples), groupId)

  clamanized_peakgroups <- claman::process_mzroll_identify_peakgroups(
    clamanized_peakgroups,
    only_identified = TRUE
  )

  possible_peakgroup_reduced_vars <- c(
    "groupId",
    "compoundName",
    "smiles",
    "adductName",
    "tagString",
    "is_unknown",
    "mz",
    "rt",
    "systematicCompoundId",
    "compoundDB",
    "searchTableName",
    "label"
  )

  detected_peakgroup_reduced_vars <- intersect(
    possible_peakgroup_reduced_vars,
    colnames(clamanized_peakgroups)
  )

  clamanized_peakgroups <- clamanized_peakgroups %>%
    dplyr::select(!!!rlang::syms(detected_peakgroup_reduced_vars)) %>%
    dplyr::group_by(compoundName) %>%
    dplyr::mutate(
      peak_label = dplyr::case_when(
        dplyr::n() == 1 ~ compoundName,
        TRUE ~ paste0(compoundName, " (", 1:dplyr::n(), ")")
      )
    ) %>%
    dplyr::ungroup() %>%
    dplyr::mutate(method_tag = method_tag) %>%
    dplyr::arrange(groupId)

  # clamanize samples
  clamanized_samples <- samples %>%
    dplyr::arrange(sampleId) %>%
    dplyr::mutate(
      sampleId = factor(sampleId, levels = sampleId)
    )

  # Need to create a version where groupId is not a factor (for joining)
  # as well as on where groupId is a factor (for validation)
  clamanized_peakgroups_final <- clamanized_peakgroups %>%
    dplyr::mutate(groupId = factor(groupId, levels = groupId)) %>%
    dplyr::mutate(smiles = "")

  # clamanize peaks
  clamanized_peaks <- updated_peaks %>%
    dplyr::mutate(groupId = as.integer(groupId)) %>%
    dplyr::arrange(groupId, sampleId) %>%
    dplyr::mutate(quant_value = !!sym(quant_type)) %>%
    dplyr::mutate(quant_value = as.numeric(quant_value)) %>%
    dplyr::group_by(groupId) %>%
    dplyr::mutate(
      log2_abundance = log2(quant_value),
      centered_log2_abundance = log2_abundance - mean(log2_abundance)
    ) %>%
    dplyr::select(
      groupId,
      sampleId,
      log2_abundance,
      centered_log2_abundance
    ) %>%
    dplyr::ungroup() %>%
    dplyr::mutate(
      groupId = factor(
        groupId,
        levels = levels(clamanized_peakgroups_final$groupId)
      ),
      sampleId = factor(
        sampleId,
        levels = levels(clamanized_samples$sampleId)
      )
    )

  # validation test
  clamanized_peaks_check <- clamanized_peaks %>%
    dplyr::mutate(groupId = as.integer(groupId)) %>%
    dplyr::group_by(groupId, sampleId) %>%
    dplyr::mutate(n = dplyr::n()) %>%
    dplyr::ungroup() %>%
    dplyr::filter(n > 1)

  mzroll_list <- romic::create_triple_omic(
    measurement_df = clamanized_peaks,
    feature_df = clamanized_peakgroups_final,
    sample_df = clamanized_samples,
    feature_pk = "groupId",
    sample_pk = "sampleId",
    omic_type_tag = "mzroll"
  )

  return(mzroll_list)
}

#' Normalize isotope matrix to sample \code{[M+0]}
#'
#' @description
#' Divide all non-M0 isotopes by M0 isotope abundance.
#' \code{NA} values are retained as \code{NA}.
#' Peaks are re-quantified to correspond to the sum of the isotopic envelope, across samples.
#'
#' @return norm_isotope_matrix normalized isotope matrix
#' @export
to_M0_normalized_isotope_matrix <- function(
  isotope_matrix
) {
  isotope_matrix_norm <- isotope_matrix

  norm_col <- isotope_matrix[, "C12 PARENT"]
  cols_to_norm <- colnames(isotope_matrix)
  cols_to_norm <- cols_to_norm[cols_to_norm != "sample"]

  for (col_to_norm in cols_to_norm) {
    isotope_matrix_norm[, col_to_norm] <- isotope_matrix[, col_to_norm] /
      norm_col
  }

  return(isotope_matrix_norm)
}

#' Isotope-specific design matrix
#'
#' @description
#' Generate a linear-model ready design matrix from a peak group isotope_matrix,
#' specific isotope, and categorizations related to samples data.
#'
#' The specific quantified isotope is renamed to 'Measurement'.
#'
#' The quant values are also \code{log2}-transformed.
#' Any \code{NA}-values are filtered out.
#'
#' @returns design_matrix DataFrame consisting of 3 columns: \code{Measurement},
#' \code{Treatment}, and \code{Time}. The implied reference conditions are
#' understood to be \code{treatment} and \code{t_early}.
#' The provided columns are non-reference factor levels.
#'
#' @export
to_emergent_isotope_design_matrix <- function(
  isotope_matrix,
  isotope_name,
  t_early_control_samples,
  t_early_treatment_samples,
  t_late_control_samples,
  t_late_treatment_samples
) {
  # adjust data frame appropriately
  design_matrix <- isotope_matrix %>%
    # remove any samples that are not covered by the quant matrix
    dplyr::filter(
      sample %in%
        t_early_control_samples |
        sample %in% t_late_control_samples |
        sample %in% t_early_treatment_samples |
        sample %in% t_late_treatment_samples
    ) %>%
    # add logic colums
    dplyr::mutate(
      Treatment = as.integer(
        sample %in%
          t_early_treatment_samples |
          sample %in% t_late_treatment_samples
      )
    ) %>%
    dplyr::mutate(
      Time = as.integer(
        sample %in%
          t_late_control_samples |
          sample %in% t_late_treatment_samples
      )
    ) %>%
    # rename and transform quant data
    dplyr::rename(Measurement := !!rlang::sym(isotope_name)) %>%
    dplyr::mutate(Measurement = log2(Measurement)) %>%
    # remove quantities that are not evaluatable
    dplyr::filter(!is.na(Measurement)) %>%
    dplyr::select(Measurement, Treatment, Time)

  return(design_matrix)
}

#' Determine Isotopic Incorporation
#'
#' @description
#' Determine peak groups where isotopic incorporation has occurred.
#' Each peak group is assessed using two separate tests:
#' \code{t_early} is compared to \code{t_late} for both the \code{control} sample subset
#' and the \code{treatment} sample subset.
#' The comparison is made by determining the fractional contribution of the \code{[M+0]} species
#' in each sample, and then carrying out a Welch t-test comparing \code{t_early} to \code{t_late}
#' in each separate \code{control} and \code{treatment} sample subset.
#' If either subset is significant, the feature is annotated as having undergone isotopic incorporation.
#' A threshold for significane is provided, which by default is \code{-log10(0.05) = 1.30103}.
#'
#' @param mzrolldb_file_path full path to mzrollDB file, which should already exist
#' and contain peak groups with isotopic envelopes.
#' @param isotope_quant_measurement_type Specific quant type used for evaluation.
#' For example, \code{peakArea}, \code{peakAreaTop}, \code{smoothedPeakArea}, or \code{peakIntensity}.
#' @param t_early_control_samples vector of sample names corresponding to \code{(t_early, control)} covariates.
#' @param t_early_treatment_samples vector of sample names corresponding to \code{(t_early, treatment)} covariates.
#' @param t_late_control_samples vector of sample names corresponding to \code{(t_late, control)} covariates.
#' @param t_late_treatment_samples vector of samples names corresponding to \code{(t_late, treatment)} covariates.
#' @param sample_order vector of all sample names, in desired order. Will be used for various sample display metrics.
#'
#' @returns table of annotated results containing columns \code{groupId}, \code{groupMz}, \code{groupRt},
#' \code{compoundName}, \code{adductName}, \code{ms2Score}, \code{groupRank}, \code{subset}, and \code{is_isotopic_incorporation}.
#' \code{groupRank} is used for the isotopic incorporation score.
#'
#' @export
compute_isotopic_incorporation <- function(
  mzrolldb_file_path,
  isotope_quant_measurement_type,
  t_early_control_samples,
  t_early_treatment_samples,
  t_late_control_samples,
  t_late_treatment_samples,
  sample_order,
  incorporation_score_threshold = 1.30103 # -log10(0.05)
) {
  iso_matrices_df <- get_precomputed_iso_df(
    iso_mzrolldb_file = mzrolldb_file_path,
    isotope_quant_measurement_type = isotope_quant_measurement_type,
    is_fractional_abundance = TRUE,
    sample_order = sample_order
  )

  iso_matrices_df_header <- iso_matrices_df %>%
    dplyr::select(
      groupId,
      groupMz,
      groupRt,
      compoundName,
      adductName,
      ms2Score
    ) %>%
    dplyr::distinct()

  iso_matrices_list <- to_iso_matrices(iso_matrices_df)

  # Control t_early vs Control t_late
  incorporation_scores_control <- purrr::map(
    iso_matrices_list,
    metisotopes::diff_iso_m_plus_zero_fraction_WelchTTest,
    t_early_control_samples,
    t_late_control_samples
  )

  control_scores_tibble <- tibble::tibble(
    groupId = as.integer(names(incorporation_scores_control)),
    groupRank = unlist(incorporation_scores_control),
    subset = "Control"
  ) %>%
    dplyr::inner_join(iso_matrices_df_header, by = c("groupId"))

  # Treatment t_early vs Treatment t_late
  incorporation_scores_treatment <- purrr::map(
    iso_matrices_list,
    metisotopes::diff_iso_m_plus_zero_fraction_WelchTTest,
    t_early_treatment_samples,
    t_late_treatment_samples
  )

  treatment_scores_tibble <- tibble::tibble(
    groupId = as.integer(names(incorporation_scores_treatment)),
    groupRank = unlist(incorporation_scores_treatment),
    subset = "Treatment"
  ) %>%
    dplyr::inner_join(iso_matrices_df_header, by = c("groupId"))

  # Agglomerated incorporation score list - significant in either case
  isotopic_incorporation_scores <- rbind(
    control_scores_tibble,
    treatment_scores_tibble
  ) %>%
    dplyr::arrange(desc(groupRank)) %>%
    dplyr::select(
      groupId,
      groupMz,
      groupRt,
      compoundName,
      adductName,
      ms2Score,
      groupRank,
      subset
    ) %>%
    dplyr::mutate(
      is_isotopic_incorporation = groupRank >= incorporation_score_threshold
    )

  return(isotopic_incorporation_scores)
}

#' Subset Diff Scores
#'
#' @description
#' This step should follow isotopic incorporation, and as it requires as an input the
#' \code{isotopic_incorporation_scores} computed by \code{compute_isotopic_incorporation()}.
#'
#' For each isotope associatd with each feature,
#' control and treatment subsets are determined. Each subset is separately subjected to a Welch t-test.
#' Then, the absolute score difference is taken of the \code{-log10(p-value)} from each test.
#' Mathematically, this is equivalent to a ratio of p-values.
#' If insufficient measurements are available to make a test, the score for one covariate subset is \code{0}.
#'
#' This test may be useful for cases where more complex, integrated statistical tests might not be
#' computable. However, this function should probably be used in conjunction with the standard approach,
#' which constructs a linear model containing all samples/information (see \code{compute_time_emergent_diff_linear_model()}).
#'
#' @param incorporation_subset list of isotope matrices that should be assessed for differences.
#' @param sig_isotopic_incorporation_scores tibble containing scores information, filtered tibble from \code{compute_isotopic_incorporation()}
#' @param t_early_control_samples vector of sample names corresponding to \code{(t_early, control)} covariates.
#' @param t_early_treatment_samples vector of sample names corresponding to \code{(t_early, treatment)} covariates.
#' @param t_late_control_samples vector of sample names corresponding to \code{(t_late, control)} covariates.
#' @param t_late_treatment_samples vector of samples names corresponding to \code{(t_late, treatment)} covariates.
#' @param sample_order vector of all sample names, in desired order. Will be used for various sample display metrics.
#' @param score_diff_threshold threshold for determining signficance. By default, \code{-log10(0.05) = 1.30103}.
#'
#' @returns design_matrix DataFrame consisting of 3 columns: \code{Measurement},
#' \code{Treatment}, and \code{Time}. The implied reference conditions are
#' understood to be \code{treatment} and \code{t_early}.
#' The provided columns are non-reference factor levels.
#'
#' @export
compute_diff_scores <- function(
  incorporation_subset,
  sig_isotopic_incorporation_scores,
  t_early_control_samples,
  t_early_treatment_samples,
  t_late_control_samples,
  t_late_treatment_samples,
  sample_order,
  score_diff_threshold = 1.30103 # -log10(0.05)
) {
  # Treatment t_early vs Control t_early
  treatment_vs_control_t_early <- purrr::map(
    incorporation_subset,
    diff_iso_all_isotopes_WelchTTest,
    t_early_control_samples,
    t_early_treatment_samples
  )
  treatment_vs_control_t_early_tibble <- dplyr::bind_rows(
    treatment_vs_control_t_early,
    .id = "groupId"
  ) %>%
    dplyr::rename(unlabeled_score = score)

  # Treatment t_late vs Control t_late
  treatment_vs_control_t_late <- purrr::map(
    incorporation_subset,
    diff_iso_all_isotopes_WelchTTest,
    t_late_control_samples,
    t_late_treatment_samples
  )

  treatment_vs_control_t_late_tibble <- dplyr::bind_rows(
    treatment_vs_control_t_late,
    .id = "groupId"
  ) %>%
    dplyr::rename(labeled_score = score)

  treatment_vs_control_combined <- dplyr::full_join(
    treatment_vs_control_t_early_tibble,
    treatment_vs_control_t_late_tibble,
    by = c("groupId", "isotope")
  ) %>%
    dplyr::mutate(score_diff = abs(unlabeled_score - labeled_score)) %>%
    dplyr::mutate(groupId = as.integer(groupId)) %>%
    dplyr::arrange(desc(score_diff))

  treatment_vs_control_w_header <- treatment_vs_control_combined %>%
    dplyr::inner_join(
      sig_isotopic_incorporation_scores,
      by = c("groupId"),
      relationship = "many-to-many"
    ) %>%
    dplyr::rename(
      incorporation_subset = subset,
      score_t_late = labeled_score,
      score_t_early = unlabeled_score
    )

  diff_scores <- treatment_vs_control_w_header %>%
    dplyr::mutate(is_high_score_diff = score_diff >= score_diff_threshold)

  return(diff_scores)
}

#' @param incorporation_subset list of isotope matrices that should be assessed for differences.
#'
#' @export
compute_time_emergent_diff_linear_model <- function(
  incorporation_subset,
  t_early_control_samples,
  t_early_treatment_samples,
  t_late_control_samples,
  t_late_treatment_samples,
  sample_order,
  p_val_interaction_threshold = 0.10,
  p_val_t_early_threshold = 0.05,
  p_val_t_late_threshold = 0.05,
  is_filter_M0_normalize = TRUE
) {
  emergent_significance_no_M0_norm <- purrr::map(
    incorporation_subset,
    diff_iso_emergent_significance,
    FALSE,
    t_early_control_samples,
    t_late_control_samples,
    t_early_treatment_samples,
    t_late_treatment_samples
  )

  emergent_significance_no_M0_norm_tibble <- dplyr::bind_rows(
    emergent_significance_no_M0_norm,
    .id = "groupId"
  ) %>%
    dplyr::mutate(is_M0_normalize = FALSE)

  emergent_significance_M0_norm <- purrr::map(
    incorporation_subset,
    diff_iso_emergent_significance,
    TRUE,
    t_early_control_samples,
    t_late_control_samples,
    t_early_treatment_samples,
    t_late_treatment_samples
  )

  emergent_significance_M0_norm_tibble <- dplyr::bind_rows(
    emergent_significance_M0_norm,
    .id = "groupId"
  ) %>%
    dplyr::mutate(is_M0_normalize = TRUE)

  combined_emergent_significance <- rbind(
    emergent_significance_no_M0_norm_tibble,
    emergent_significance_M0_norm_tibble
  ) %>%
    dplyr::mutate(emergentScore = -log10(p_val_late_diff)) %>%
    dplyr::arrange(desc(emergentScore))

  lm_scores <- combined_emergent_significance %>%
    # Remove NA values
    dplyr::filter(
      !is.na(p_val_interaction) &
        !is.na(p_val_early_diff) &
        !is.na(p_val_late_diff)
    ) %>%
    # (1) delta between treatment and control changes between t_early and t_late
    dplyr::mutate(
      is_p_val_interaction = p_val_interaction <= p_val_interaction_threshold
    ) %>%
    # (2) treatment and control is not different in t_early
    dplyr::mutate(
      is_p_val_early_diff = p_val_early_diff >= p_val_t_early_threshold
    ) %>%
    # (3) treatment and control is different in t_late
    dplyr::mutate(
      is_p_val_late_diff = p_val_late_diff <= p_val_t_late_threshold
    ) %>%
    # Sample-specific normalization to M0
    dplyr::filter(
      !is_filter_M0_normalize | (is_filter_M0_normalize & is_M0_normalize)
    )

  return(lm_scores)
}
