name: Format and lint R code

on:
  workflow_dispatch:
    inputs:
      working-dir:
        required: false
        description: "Directory containing R package"
        type: string
        default: "."
      auto-format-enabled:
        required: false
        description: "Enable auto-formatting"
        type: boolean
        default: false
  push:
    paths-ignore:
      - "*.Rd"
      - "*.png"

jobs:
  run-r-lint-format:
    name: Style metisotopes R package
    uses: ./.github/workflows/r-lint-format-action.yml
    with:
      working-dir: ${{ inputs.working-dir || '.' }}
      auto-format-enabled: ${{ inputs.auto-format-enabled || false }}
    secrets: inherit
